### ISSUE TITLE
FEATURE - Create Response Models

### ISSUE THREAD

**Issue by BrentMifsud** [Coding-Couch/tendr#12]
- [x] Meme Response - Coding-Couch/tendr-api#4
- [x] Meme Sorted -  Coding-Couch/tendr-api#5
- [x] Meme Downvote -  Coding-Couch/tendr-api#3
- [x] Meme Upvote - Coding-Couch/tendr-api#2
- [x] Meme Signup - Coding-Couch/tendr-api#1
